def AM(a):
    if a == "a":
        return "1q2w3e4r" + a
    elif a == "b":
        return "1a2s3d4f" + a
    elif a == "c":
        return "1z2x3c4v" + a
    elif a == "d":
        return "2q3w4e5r" + a
    elif a == "e":
        return "2a3s4d5f" + a
    elif a == "f":
        return "2z3x4c5" + a
    elif a == "g":
        return "3q4w5e6r" + a
    elif a == "h":
        return "3a4s5d6f" + a
    elif a == "i":
        return "3z4x5c6v" + a
    elif a == "j":
        return "4q5w6e7r" + a
    elif a == "k":
        return "4a5s6d7f" + a
    elif a == "l":
        return "4z5x6c7v" + a
    elif a == "m":
        return "5w6e7e8r" + a
    elif a == "n":
        return "5a6s7d8f" + a
    elif a == "o":
        return "5z6x7c8v" + a
    elif a == "p":
        return "6q7w8e9r" + a
    elif a == "q":
        return "6a7s8d9f" + a
    elif a == "r":
        return "6z7x8c9v" + a
    elif a == "s":
        return "7q8w9e0r" + a
    elif a == "t":
        return "7a8s9d0f" + a
    elif a == "u":
        return "7z8x9c0v" + a
    elif a == "w":
        return "1w2e3r4t" + a
    elif a == "x":
        return "1s2d3f4g" + a
    elif a == "y":
        return "1x2c3v4b" + a
    elif a == "z":
        return "2w3e4r5t" + a
    elif a == "1":
        return "2s3d4f5g" + a
    elif a == "2":
        return "2x3c4v5b" + a
    elif a == "3":
        return "3w4e5r6t" + a
    elif a == "4":
        return "3s4d5f6g" + a
    elif a == "5":
        return "3x4c5v6b" + a
    elif a == "6":
        return "4w5e6r7t" + a
    elif a == "7":
        return "4s5d6f7g" + a
    elif a == "8":
        return "4x5c6v7b" + a
    elif a == "9":
        return "5e6e7r8t" + a
    elif a == "0":
        return "5s6d7f8g" + a
